const REPO_OWNER="lomankam";
const REPO_NAME="WingChun";
const DEFAULT_BRANCH="main";
const VIDEO_IDS_PATH="data/videoIds.json";
const WCMD_PATH="data/wcmd.json";
const TERMINOLOGY_PATH="data/terminology.json";
const DEFAULT_AI_MODEL="@cf/qwen/qwen3-30b-a3b-fp8";
const MAX_AI_INPUT=12000;
const publicBase=`https://${REPO_OWNER}.github.io/${REPO_NAME}`;
const corsHeaders={
  "Access-Control-Allow-Origin":"*",
  "Access-Control-Allow-Methods":"GET, POST, OPTIONS",
  "Access-Control-Allow-Headers":"Content-Type, Authorization",
  "Cache-Control":"no-store"
};
function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{"Content-Type":"application/json; charset=utf-8",...corsHeaders}});}
function today(){return new Date().toISOString().slice(0,10);}
function cleanTitle(raw=""){return String(raw).trim().replace(/^盧[文⽂]錦\s*師[父⽗]\s*授課精華\s*[0-9]+\s*[\-－–—｜|：:]?\s*/u,"").replace(/^授課精華\s*[0-9]+\s*[\-－–—｜|：:]?\s*/u,"").replace(/^[\s\-－–—•●▪◆★]+/u,"").trim();}
function utf8ToBase64(str){const bytes=new TextEncoder().encode(str);let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary);}
function base64ToUtf8(b64){const binary=atob(String(b64||"").replace(/\n/g,""));const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new TextDecoder().decode(bytes);}
function extractVideoId(input=""){const text=String(input||"").trim();if(!text)return"";try{const u=new URL(text);if(u.hostname.includes("youtu.be"))return u.pathname.replace(/^\//,"").split("?")[0];if(u.searchParams.get("v"))return u.searchParams.get("v");const p=u.pathname.split("/").filter(Boolean);const i=p.findIndex(x=>["shorts","embed","live"].includes(x));if(i>=0&&p[i+1])return p[i+1];}catch(_){}return text;}
function extractEpisode(title=""){const m=String(title||"").match(/授課精華\s*([0-9]+)/);return m?Number(m[1]):null;}
function toVideo(item,includeDescription=false){const s=item.snippet||{},id=item.id;const v={episode:extractEpisode(s.title),title:cleanTitle(s.title||""),url:`https://youtu.be/${id}`,videoId:id,channelId:s.channelId||"",publishedAt:s.publishedAt||"",thumbnail:s.thumbnails?.maxres?.url||s.thumbnails?.high?.url||s.thumbnails?.medium?.url||s.thumbnails?.default?.url||""};if(includeDescription)v.description=s.description||"";return v;}
async function fetchVideosByIds(env,ids,includeDescription=false){if(!env.YOUTUBE_API_KEY)throw new Error("Missing YOUTUBE_API_KEY");const clean=[...new Set(ids.map(String).filter(Boolean))],all=[];for(let i=0;i<clean.length;i+=50){const c=clean.slice(i,i+50);const api=`https://www.googleapis.com/youtube/v3/videos?part=snippet&id=${c.join(",")}&key=${env.YOUTUBE_API_KEY}`;const res=await fetch(api);const data=await res.json();if(!res.ok)throw new Error(JSON.stringify(data));all.push(...(data.items||[]));}return all.map(x=>toVideo(x,includeDescription)).filter(v=>v.videoId).sort((a,b)=>(b.episode||0)-(a.episode||0));}
async function fetchOneVideo(env,input){const id=extractVideoId(input);if(!id)throw new Error("Missing video ID or YouTube URL");const v=await fetchVideosByIds(env,[id],true);if(!v.length)throw new Error("Video not found. Check URL, privacy setting, or API access.");return v[0];}
async function publicJson(path,fallback){try{const res=await fetch(`${publicBase}/${path}?v=${Date.now()}`,{cf:{cacheTtl:0}});if(!res.ok)throw new Error();return await res.json();}catch(_){return fallback;}}
async function getVideoIds(){const data=await publicJson(VIDEO_IDS_PATH,[]);const ids=Array.isArray(data)?data:(data.videoIds||data.ids||[]);return [...new Set((ids||[]).map(String).filter(Boolean))];}
async function getTerminology(){return await publicJson(TERMINOLOGY_PATH,{version:0,terms:{}});}
async function youtubeJson(env,path,params={}){if(!env.YOUTUBE_API_KEY)throw new Error("Missing YOUTUBE_API_KEY");const query=new URLSearchParams({...params,key:env.YOUTUBE_API_KEY});const res=await fetch(`https://www.googleapis.com/youtube/v3/${path}?${query}`);const data=await res.json();if(!res.ok)throw new Error(`YouTube API failed: ${JSON.stringify(data)}`);return data;}
async function getUploadsPlaylistId(env){if(env.YOUTUBE_UPLOADS_PLAYLIST_ID)return String(env.YOUTUBE_UPLOADS_PLAYLIST_ID);let channelId=String(env.YOUTUBE_CHANNEL_ID||"").trim();if(!channelId){const ids=await getVideoIds();if(ids.length){const videos=await fetchVideosByIds(env,[ids[0]],false);channelId=String(videos[0]?.channelId||"").trim();}}if(!channelId)return"";const data=await youtubeJson(env,"channels",{part:"contentDetails",id:channelId});return String(data.items?.[0]?.contentDetails?.relatedPlaylists?.uploads||"");}
async function fetchLatestUploads(env,playlistId){const data=await youtubeJson(env,"playlistItems",{part:"snippet,contentDetails",playlistId,maxResults:"50"});return (data.items||[]).map(item=>String(item.contentDetails?.videoId||item.snippet?.resourceId?.videoId||"")).filter(Boolean);}
function terminologyLines(terminology){return Object.entries(terminology?.terms||{}).map(([key,t])=>{const zh=String(t?.zh||key).trim(),en=String(t?.official_en||t?.en||"").trim(),legacy=Array.isArray(t?.legacy_en)?t.legacy_en.filter(Boolean):[];return en?`${zh} = ${en}${legacy.length?`（舊用字：${legacy.join("、")}）`:""}`:"";}).filter(Boolean);}
function glossaryInstruction(terminology){const lines=terminologyLines(terminology);return[`官方術語字典版本：${Number(terminology?.version)||0}`,"術語使用規則：只要中文內容包含字典術語，英文必須使用 official_en；不要自行改寫或翻譯已核准術語；未知術語請標記為待確認。",lines.length?`官方術語對照：\n${lines.join("\n")}`:"官方術語字典目前沒有可用資料。"].join("\n");}
function aiText(result){if(typeof result==="string")return result.trim();return String(result?.response||result?.result?.response||result?.output_text||"").trim();}
function languageInstructionFromMessage(message){const marker="使用者這次的問題：",index=String(message||"").lastIndexOf(marker),question=String(message||"").slice(index>=0?index+marker.length:0).trim();if(/[ぁ-ゖァ-ヺ]/u.test(question))return"回答語言：請完整使用日文回答。";if(/[가-힣]/u.test(question))return"回答語言：請完整使用韓文回答。";if(/[一-鿿]/u.test(question))return"回答語言：請完整使用繁體中文回答。";if(/[A-Za-z]/.test(question))return"回答語言：請完整使用英文回答。";return"回答語言：請使用與提問者相同的語言回答。";}
function cleanAiTitle(text){return String(text||"").replace(/^```[a-z]*\s*/i,"").replace(/```$/g,"").replace(/^\s*["'「『]|["'」』]\s*$/g,"").split(/[\n\r]/)[0].trim().slice(0,240);}
function applyGlossary(text,terminology){let result=String(text||"");const terms=Object.entries(terminology?.terms||{}).map(([key,t])=>({zh:String(t?.zh||key),en:String(t?.official_en||t?.en||""),legacy:Array.isArray(t?.legacy_en)?t.legacy_en:[],aliases:Array.isArray(t?.aliases)?t.aliases:[]})).filter(t=>t.en).sort((a,b)=>b.zh.length-a.zh.length);for(const term of terms){for(const old of [...term.legacy,...term.aliases]){const escaped=String(old).replace(/[.*+?^${}()|[\]\\]/g,"\\$&");result=result.replace(new RegExp(escaped,"giu"),term.en);}const escapedZh=term.zh.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");result=result.replace(new RegExp(escapedZh,"gu"),term.en);}return result;}
async function generateEnglishTitle(env,titleZh,description,terminology){if(!env.AI)throw new Error("Workers AI binding is not configured");const prompt=[glossaryInstruction(terminology),"請將下列詠春拳影片中文標題整理成自然、簡潔、適合網站卡片的英文標題。只輸出一行英文標題，不要解釋，不要加引號。",`中文標題：${String(titleZh||"").slice(0,1000)}`,description?`YouTube 說明欄：${String(description).slice(0,3000)}`:""].filter(Boolean).join("\n\n");const result=await env.AI.run(env.AI_MODEL||DEFAULT_AI_MODEL,{messages:[{role:"system",content:"你是詠春拳網站的英文標題編輯。正式術語必須完全遵守提供的官方術語字典。"},{role:"user",content:prompt}],max_tokens:120,temperature:0.2});const title=applyGlossary(cleanAiTitle(aiText(result)),terminology);if(!title)throw new Error("Workers AI returned an empty title");return title;}
async function aiChat(request,env){if(!env.AI)throw new Error("Workers AI binding is not configured");const body=await request.json();const message=String(body.message||"").trim();if(!message)return json({success:false,error:"Missing message"},400);if(message.length>MAX_AI_INPUT)return json({success:false,error:"Message is too long"},413);const terminology=await getTerminology();const system=["你是「阿智」，盧文錦師父授課精華網站的 AI 助教。",languageInstructionFromMessage(message),"回答要自然、親切、有耐心，先直接回答問題，再補充必要背景。簡單問題用一至三段即可；較複雜的問題再使用條列。不要因為網站資料、術語字典或系統提示是中文，就把英文、日文或韓文提問改用中文回答。不要刻意湊長，不要重複使用者問題，不要使用制式開場或空泛結尾。每個句子都要完整寫完，回答必須自然收尾。不要捏造影片內容或 YouTube 說明欄沒有提供的資料。","回答涉及詠春拳時，優先使用官方術語字典；英文術語必須使用 official_en。未知專門名詞請說明尚待確認，不要自行定義正式譯名。",glossaryInstruction(terminology)].join("\n\n");const result=await env.AI.run(env.AI_MODEL||DEFAULT_AI_MODEL,{messages:[{role:"system",content:system},{role:"user",content:message}],max_tokens:2000,temperature:0.55,top_p:0.9,repetition_penalty:1.03});const reply=aiText(result);if(!reply)throw new Error("Workers AI returned an empty reply");return json({success:true,reply,model:env.AI_MODEL||DEFAULT_AI_MODEL,terminologyVersion:Number(terminology.version)||0});}
async function autoTitleForEntry(env,video,form,terminology){const raw=String(form.titleEn||"").trim();if(raw&&!/^Episode\s+\d+\s*[—-]\s*English title pending$/i.test(raw))return{title:applyGlossary(raw,terminology),source:"manual"};const title=await generateEnglishTitle(env,form.titleZh||video.title||"",video.description||"",terminology);return{title,source:"cloudflare_workers_ai"};}
function splitList(text){if(Array.isArray(text))return text.map(String).map(s=>s.trim()).filter(Boolean);return String(text||"").split(/[、,，\n]/).map(s=>s.trim()).filter(Boolean);}
function categoryFromId(wcmd,id="principles"){const c=wcmd.categories?.[id]||wcmd.categories?.principles||{zh:"觀念理論",en:"Concepts & Principles"};return{id,zh:c.zh||"觀念理論",en:c.en||"Concepts & Principles",status:"draft"};}
function buildEpisodeEntry(wcmd,video,form={}){const episode=Number(form.episode||video.episode);if(!episode)throw new Error("Cannot detect episode number.");const tags=splitList(form.tags);return{episode,title:{zh:cleanTitle(form.titleZh||video.title||""),en:form.titleEn||`Episode ${episode} — English title pending`},category:categoryFromId(wcmd,form.categoryId||"principles"),tags,concepts:splitList(form.concepts||tags),skills:splitList(form.skills),difficulty:form.difficulty||"to_be_confirmed",summary:{zh:form.summaryZh||"",en:form.summaryEn||""},youtube:{videoId:video.videoId,url:video.url,thumbnail:video.thumbnail||"",publishedAt:video.publishedAt||""},dataStatus:{youtubeBasic:"confirmed_from_youtube_api",titleEn:form.titleEn?"confirmed":"pending",titleEnSource:form.titleEnSource||"manual",terminologyVersion:Number(form.terminologyVersion||0),category:"draft",updatedAt:today()}};}
function ghHeaders(env){return{"Authorization":`Bearer ${env.GITHUB_TOKEN}`,"Accept":"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"WingChun-Admin-Publisher"};}
async function ghGetFile(env,path){const branch=env.GITHUB_BRANCH||DEFAULT_BRANCH,api=`https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${path}?ref=${encodeURIComponent(branch)}`;const res=await fetch(api,{headers:ghHeaders(env)});if(res.status===404)return{sha:null,data:null};const data=await res.json();if(!res.ok)throw new Error(`GitHub get failed: ${JSON.stringify(data)}`);return{sha:data.sha,data:JSON.parse(base64ToUtf8(data.content||""))};}
async function ghPutFile(env,path,obj,message,sha=null){const branch=env.GITHUB_BRANCH||DEFAULT_BRANCH,api=`https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${path}`,payload={message,content:utf8ToBase64(JSON.stringify(obj,null,2)+"\n"),branch};if(sha)payload.sha=sha;const res=await fetch(api,{method:"PUT",headers:{...ghHeaders(env),"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(`GitHub update failed: ${JSON.stringify(data)}`);return data;}
async function hmac(secret,text){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(text));return btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
async function createSession(env){if(!env.ADMIN_PASSWORD)throw new Error("ADMIN_PASSWORD is not configured");const payload={exp:Date.now()+2*60*60*1000,nonce:crypto.randomUUID()};const body=btoa(JSON.stringify(payload)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");const sig=await hmac(env.ADMIN_PASSWORD,body);return `${body}.${sig}`;}
async function verifySession(env,request){if(!env.ADMIN_PASSWORD)return false;const auth=request.headers.get("Authorization")||"";const token=auth.replace(/^Bearer\s+/i,"");const [body,sig]=token.split(".");if(!body||!sig)return false;const expected=await hmac(env.ADMIN_PASSWORD,body);if(sig!==expected)return false;try{const json=JSON.parse(atob(body.replace(/-/g,"+").replace(/_/g,"/")));return Number(json.exp)>Date.now();}catch(_){return false;}}
async function requireSession(env,request){if(!(await verifySession(env,request)))throw new Error("Unauthorized");if(!env.GITHUB_TOKEN)throw new Error("Missing GITHUB_TOKEN");}
async function publishEpisode(request,env){await requireSession(env,request);const body=await request.json();const video=body.video?.videoId?body.video:await fetchOneVideo(env,body.videoUrl||body.url||body.id||"");const terminology=await getTerminology();const form={...(body.entry||{})};const generated=await autoTitleForEntry(env,video,form,terminology);form.titleEn=generated.title;form.titleEnSource=generated.source;form.terminologyVersion=Number(terminology.version)||0;const [idsFile,wcmdFile]=await Promise.all([ghGetFile(env,VIDEO_IDS_PATH),ghGetFile(env,WCMD_PATH)]);const ids=[...new Set([...(Array.isArray(idsFile.data)?idsFile.data:[]),video.videoId])];let wcmd=wcmdFile.data||{schemaVersion:"1.0",categories:{},episodes:[]};if(!Array.isArray(wcmd.episodes))wcmd.episodes=[];const entry=buildEpisodeEntry(wcmd,video,form);const idx=wcmd.episodes.findIndex(e=>Number(e.episode)===entry.episode);if(idx>=0)wcmd.episodes[idx]={...wcmd.episodes[idx],...entry};else wcmd.episodes.push(entry);wcmd.episodes.sort((a,b)=>Number(a.episode)-Number(b.episode));wcmd.platformVersion="V26.0";wcmd.generatedAt=today();const msg=`Admin: publish episode ${entry.episode}`;await ghPutFile(env,VIDEO_IDS_PATH,ids,`${msg} videoIds`,idsFile.sha);await ghPutFile(env,WCMD_PATH,wcmd,`${msg} WCMD`,wcmdFile.sha);return json({success:true,message:`Episode ${entry.episode} published. GitHub Pages may take 1–3 minutes.`,videoIdsCount:ids.length,episode:entry});}
async function syncYouTubeUploads(env){if(!env.YOUTUBE_API_KEY||!env.GITHUB_TOKEN||!env.AI)return{skipped:true,reason:"Missing YOUTUBE_API_KEY, GITHUB_TOKEN, or Workers AI binding"};const playlistId=await getUploadsPlaylistId(env);if(!playlistId)return{skipped:true,reason:"Missing YouTube uploads playlist"};const latestIds=await fetchLatestUploads(env,playlistId);if(!latestIds.length)return{added:0};const [idsFile,wcmdFile]=await Promise.all([ghGetFile(env,VIDEO_IDS_PATH),ghGetFile(env,WCMD_PATH)]);const existingIds=new Set((Array.isArray(idsFile.data)?idsFile.data:[]).map(String));const newIds=latestIds.filter(id=>!existingIds.has(id));if(!newIds.length)return{added:0};const videos=await fetchVideosByIds(env,newIds,true);const terminology=await getTerminology();let wcmd=wcmdFile.data||{schemaVersion:"1.0",categories:{},episodes:[]};if(!Array.isArray(wcmd.episodes))wcmd.episodes=[];const added=[];for(const video of videos){if(!video.episode)continue;const existing=wcmd.episodes.find(e=>Number(e.episode)===Number(video.episode));if(existing)continue;const form={episode:video.episode,titleZh:video.title,titleEnSource:"cloudflare_workers_ai",categoryId:"principles",tags:[],concepts:[],skills:[],difficulty:"to_be_confirmed",summaryZh:"",summaryEn:""};form.titleEn=await generateEnglishTitle(env,video.title,video.description||"",terminology);const entry=buildEpisodeEntry(wcmd,video,{...form,terminologyVersion:Number(terminology.version)||0});wcmd.episodes.push(entry);added.push(video.videoId);}
if(!added.length)return{added:0,detected:newIds.length};wcmd.episodes.sort((a,b)=>Number(a.episode)-Number(b.episode));wcmd.platformVersion="V26.0";wcmd.generatedAt=today();const ids=[...new Set([...existingIds,...added])];const msg=`Scheduled YouTube sync: ${added.length} episode(s)`;await ghPutFile(env,VIDEO_IDS_PATH,ids,msg+" videoIds",idsFile.sha);await ghPutFile(env,WCMD_PATH,wcmd,msg+" WCMD",wcmdFile.sha);return{added:added.length,episodes:wcmd.episodes.filter(e=>added.includes(e.youtube?.videoId)).map(e=>e.episode)};}
export default{async scheduled(controller,env,ctx){ctx.waitUntil(syncYouTubeUploads(env).catch(error=>console.error("Scheduled YouTube sync failed",error)));},async fetch(request,env){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{headers:corsHeaders});try{
if(url.pathname==="/"||url.pathname==="/api/health")return json({success:true,service:"wingchun-sync",version:"8.2.0",status:"running",githubEnabled:Boolean(env.GITHUB_TOKEN),adminEnabled:Boolean(env.ADMIN_PASSWORD),workersAIEnabled:Boolean(env.AI),aiModel:env.AI_MODEL||DEFAULT_AI_MODEL,repo:`${REPO_OWNER}/${REPO_NAME}`});
if(url.pathname==="/api/admin/login"&&request.method==="POST"){if(!env.ADMIN_PASSWORD)return json({success:false,error:"ADMIN_PASSWORD is not configured"},503);const body=await request.json();if(body.password!==env.ADMIN_PASSWORD)return json({success:false,error:"密碼錯誤"},401);return json({success:true,token:await createSession(env),expiresIn:7200});}
if(url.pathname==="/api/admin/session")return json({success:await verifySession(env,request)},(await verifySession(env,request))?200:401);
if(url.pathname==="/api/ai/chat"&&request.method==="POST")return await aiChat(request,env);
if(url.pathname==="/api/import"){const input=url.searchParams.get("url")||url.searchParams.get("id")||"";return json({success:true,video:await fetchOneVideo(env,input)});}
if(url.pathname==="/api/admin/publish"&&request.method==="POST")return await publishEpisode(request,env);
if(url.pathname==="/api/videos"){const ids=await getVideoIds(),videos=await fetchVideosByIds(env,ids,false);return json({success:true,source:"data/videoIds.json",count:videos.length,videos});}
if(url.pathname==="/api/latest"){const ids=await getVideoIds(),videos=await fetchVideosByIds(env,ids,false);return json({success:true,latest:videos[0]||null});}
if(url.pathname.startsWith("/api/video/")){const ep=Number(url.pathname.replace("/api/video/","")),ids=await getVideoIds(),videos=await fetchVideosByIds(env,ids,true),video=videos.find(v=>v.episode===ep);return video?json({success:true,video}):json({success:false,message:`Episode ${ep} not found`},404);}
if(url.pathname==="/api/search"){const q=(url.searchParams.get("q")||"").trim().toLowerCase(),ids=await getVideoIds(),videos=await fetchVideosByIds(env,ids,true),results=q?videos.filter(v=>`${v.title} ${v.description||""}`.toLowerCase().includes(q)):[];return json({success:true,query:q,count:results.length,results});}
return json({success:false,message:"Not found"},404);
}catch(e){const msg=String(e.message||e);return json({success:false,error:msg},msg==="Unauthorized"?401:500);}}};
