const REPO_OWNER="lomankam";
const REPO_NAME="WingChun";
const DEFAULT_BRANCH="main";
const VIDEO_IDS_PATH="data/videoIds.json";
const WCMD_PATH="data/wcmd.json";
const publicBase=`https://${REPO_OWNER}.github.io/${REPO_NAME}`;
const corsHeaders={
  "Access-Control-Allow-Origin":"*",
  "Access-Control-Allow-Methods":"GET, POST, OPTIONS",
  "Access-Control-Allow-Headers":"Content-Type, Authorization",
  "Cache-Control":"no-store"
};
function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{"Content-Type":"application/json; charset=utf-8",...corsHeaders}});}
function today(){return new Date().toISOString().slice(0,10);}
function cleanTitle(raw=""){return String(raw).trim().replace(/^盧[文⽂]錦\s*師[父⽗]\s*授課精華\s*[0-9]+\s*[\-－–—｜|：:]?\s*/u,"").replace(/^授課精華\s*[0-9]+\s*[\-－–—｜|：:]?\s*/u,"").replace(/^[\s\-－–—•●▪◆★]+/u,"").trim();}
function utf8ToBase64(str){const bytes=new TextEncoder().encode(str);let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary);}
function base64ToUtf8(b64){const binary=atob(String(b64||"").replace(/\n/g,""));const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new TextDecoder().decode(bytes);}
function extractVideoId(input=""){const text=String(input||"").trim();if(!text)return"";try{const u=new URL(text);if(u.hostname.includes("youtu.be"))return u.pathname.replace(/^\//,"").split("?")[0];if(u.searchParams.get("v"))return u.searchParams.get("v");const p=u.pathname.split("/").filter(Boolean);const i=p.findIndex(x=>["shorts","embed","live"].includes(x));if(i>=0&&p[i+1])return p[i+1];}catch(_){}return text;}
function extractEpisode(title=""){const m=String(title||"").match(/授課精華\s*([0-9]+)/);return m?Number(m[1]):null;}
function toVideo(item,includeDescription=false){const s=item.snippet||{},id=item.id;const v={episode:extractEpisode(s.title),title:cleanTitle(s.title||""),url:`https://youtu.be/${id}`,videoId:id,publishedAt:s.publishedAt||"",thumbnail:s.thumbnails?.maxres?.url||s.thumbnails?.high?.url||s.thumbnails?.medium?.url||s.thumbnails?.default?.url||""};if(includeDescription)v.description=s.description||"";return v;}
async function fetchVideosByIds(env,ids,includeDescription=false){if(!env.YOUTUBE_API_KEY)throw new Error("Missing YOUTUBE_API_KEY");const clean=[...new Set(ids.map(String).filter(Boolean))],all=[];for(let i=0;i<clean.length;i+=50){const c=clean.slice(i,i+50);const api=`https://www.googleapis.com/youtube/v3/videos?part=snippet&id=${c.join(",")}&key=${env.YOUTUBE_API_KEY}`;const res=await fetch(api);const data=await res.json();if(!res.ok)throw new Error(JSON.stringify(data));all.push(...(data.items||[]));}return all.map(x=>toVideo(x,includeDescription)).filter(v=>v.videoId).sort((a,b)=>(b.episode||0)-(a.episode||0));}
async function fetchOneVideo(env,input){const id=extractVideoId(input);if(!id)throw new Error("Missing video ID or YouTube URL");const v=await fetchVideosByIds(env,[id],true);if(!v.length)throw new Error("Video not found. Check URL, privacy setting, or API access.");return v[0];}
async function publicJson(path,fallback){try{const res=await fetch(`${publicBase}/${path}?v=${Date.now()}`,{cf:{cacheTtl:0}});if(!res.ok)throw new Error();return await res.json();}catch(_){return fallback;}}
async function getVideoIds(){const data=await publicJson(VIDEO_IDS_PATH,[]);const ids=Array.isArray(data)?data:(data.videoIds||data.ids||[]);return [...new Set((ids||[]).map(String).filter(Boolean))];}
function splitList(text){if(Array.isArray(text))return text.map(String).map(s=>s.trim()).filter(Boolean);return String(text||"").split(/[、,，\n]/).map(s=>s.trim()).filter(Boolean);}
function categoryFromId(wcmd,id="principles"){const c=wcmd.categories?.[id]||wcmd.categories?.principles||{zh:"觀念理論",en:"Concepts & Principles"};return{id,zh:c.zh||"觀念理論",en:c.en||"Concepts & Principles",status:"draft"};}
function buildEpisodeEntry(wcmd,video,form={}){const episode=Number(form.episode||video.episode);if(!episode)throw new Error("Cannot detect episode number.");const tags=splitList(form.tags);return{episode,title:{zh:cleanTitle(form.titleZh||video.title||""),en:form.titleEn||`Episode ${episode} — English title pending`},category:categoryFromId(wcmd,form.categoryId||"principles"),tags,concepts:splitList(form.concepts||tags),skills:splitList(form.skills),difficulty:form.difficulty||"to_be_confirmed",summary:{zh:form.summaryZh||"",en:form.summaryEn||""},youtube:{videoId:video.videoId,url:video.url,thumbnail:video.thumbnail||"",publishedAt:video.publishedAt||""},dataStatus:{youtubeBasic:"confirmed_from_youtube_api",titleEn:form.titleEn?"confirmed":"pending",category:"draft",updatedAt:today()}};}
function ghHeaders(env){return{"Authorization":`Bearer ${env.GITHUB_TOKEN}`,"Accept":"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"WingChun-Admin-Publisher"};}
async function ghGetFile(env,path){const branch=env.GITHUB_BRANCH||DEFAULT_BRANCH,api=`https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${path}?ref=${encodeURIComponent(branch)}`;const res=await fetch(api,{headers:ghHeaders(env)});if(res.status===404)return{sha:null,data:null};const data=await res.json();if(!res.ok)throw new Error(`GitHub get failed: ${JSON.stringify(data)}`);return{sha:data.sha,data:JSON.parse(base64ToUtf8(data.content||""))};}
async function ghPutFile(env,path,obj,message,sha=null){const branch=env.GITHUB_BRANCH||DEFAULT_BRANCH,api=`https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${path}`,payload={message,content:utf8ToBase64(JSON.stringify(obj,null,2)+"\n"),branch};if(sha)payload.sha=sha;const res=await fetch(api,{method:"PUT",headers:{...ghHeaders(env),"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(`GitHub update failed: ${JSON.stringify(data)}`);return data;}
async function hmac(secret,text){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(text));return btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
async function createSession(env){if(!env.ADMIN_PASSWORD)throw new Error("ADMIN_PASSWORD is not configured");const payload={exp:Date.now()+2*60*60*1000,nonce:crypto.randomUUID()};const body=btoa(JSON.stringify(payload)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");const sig=await hmac(env.ADMIN_PASSWORD,body);return `${body}.${sig}`;}
async function verifySession(env,request){if(!env.ADMIN_PASSWORD)return false;const auth=request.headers.get("Authorization")||"";const token=auth.replace(/^Bearer\s+/i,"");const [body,sig]=token.split(".");if(!body||!sig)return false;const expected=await hmac(env.ADMIN_PASSWORD,body);if(sig!==expected)return false;try{const json=JSON.parse(atob(body.replace(/-/g,"+").replace(/_/g,"/")));return Number(json.exp)>Date.now();}catch(_){return false;}}
async function requireSession(env,request){if(!(await verifySession(env,request)))throw new Error("Unauthorized");if(!env.GITHUB_TOKEN)throw new Error("Missing GITHUB_TOKEN");}
async function publishEpisode(request,env){await requireSession(env,request);const body=await request.json();const video=body.video?.videoId?body.video:await fetchOneVideo(env,body.videoUrl||body.url||body.id||"");const [idsFile,wcmdFile]=await Promise.all([ghGetFile(env,VIDEO_IDS_PATH),ghGetFile(env,WCMD_PATH)]);const ids=[...new Set([...(Array.isArray(idsFile.data)?idsFile.data:[]),video.videoId])];let wcmd=wcmdFile.data||{schemaVersion:"1.0",categories:{},episodes:[]};if(!Array.isArray(wcmd.episodes))wcmd.episodes=[];const entry=buildEpisodeEntry(wcmd,video,body.entry||{});const idx=wcmd.episodes.findIndex(e=>Number(e.episode)===entry.episode);if(idx>=0)wcmd.episodes[idx]={...wcmd.episodes[idx],...entry};else wcmd.episodes.push(entry);wcmd.episodes.sort((a,b)=>Number(a.episode)-Number(b.episode));wcmd.platformVersion="V26.0";wcmd.generatedAt=today();const msg=`Admin: publish episode ${entry.episode}`;await ghPutFile(env,VIDEO_IDS_PATH,ids,`${msg} videoIds`,idsFile.sha);await ghPutFile(env,WCMD_PATH,wcmd,`${msg} WCMD`,wcmdFile.sha);return json({success:true,message:`Episode ${entry.episode} published. GitHub Pages may take 1–3 minutes.`,videoIdsCount:ids.length,episode:entry});}
export default{async fetch(request,env){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{headers:corsHeaders});try{
if(url.pathname==="/"||url.pathname==="/api/health")return json({success:true,service:"wingchun-sync",version:"8.0.0",status:"running",githubEnabled:Boolean(env.GITHUB_TOKEN),adminEnabled:Boolean(env.ADMIN_PASSWORD),repo:`${REPO_OWNER}/${REPO_NAME}`});
if(url.pathname==="/api/admin/login"&&request.method==="POST"){if(!env.ADMIN_PASSWORD)return json({success:false,error:"ADMIN_PASSWORD is not configured"},503);const body=await request.json();if(body.password!==env.ADMIN_PASSWORD)return json({success:false,error:"密碼錯誤"},401);return json({success:true,token:await createSession(env),expiresIn:7200});}
if(url.pathname==="/api/admin/session")return json({success:await verifySession(env,request)},(await verifySession(env,request))?200:401);
if(url.pathname==="/api/import"){const input=url.searchParams.get("url")||url.searchParams.get("id")||"";return json({success:true,video:await fetchOneVideo(env,input)});}
if(url.pathname==="/api/admin/publish"&&request.method==="POST")return await publishEpisode(request,env);
if(url.pathname==="/api/videos"){const ids=await getVideoIds(),videos=await fetchVideosByIds(env,ids,false);return json({success:true,source:"data/videoIds.json",count:videos.length,videos});}
if(url.pathname==="/api/latest"){const ids=await getVideoIds(),videos=await fetchVideosByIds(env,ids,false);return json({success:true,latest:videos[0]||null});}
if(url.pathname.startsWith("/api/video/")){const ep=Number(url.pathname.replace("/api/video/","")),ids=await getVideoIds(),videos=await fetchVideosByIds(env,ids,true),video=videos.find(v=>v.episode===ep);return video?json({success:true,video}):json({success:false,message:`Episode ${ep} not found`},404);}
if(url.pathname==="/api/search"){const q=(url.searchParams.get("q")||"").trim().toLowerCase(),ids=await getVideoIds(),videos=await fetchVideosByIds(env,ids,true),results=q?videos.filter(v=>`${v.title} ${v.description||""}`.toLowerCase().includes(q)):[];return json({success:true,query:q,count:results.length,results});}
return json({success:false,message:"Not found"},404);
}catch(e){const msg=String(e.message||e);return json({success:false,error:msg},msg==="Unauthorized"?401:500);}}};